"""initial schema

Revision ID: 9d6800a7e6c0
Revises: 
Create Date: 2026-09-02 20:29:48.749970

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9d6800a7e6c0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('stress_test_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('input_type', sa.Enum('business_plan', 'pitch', 'codebase', 'research_paper', name='input_type'), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stress_test_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('personas_used', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='run_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['stress_test_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('persona', sa.Enum('competitor', 'investor', 'hacker', 'customer', 'academic', name='persona_id'), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['stress_test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('persona_finding_id', sa.UUID(), nullable=False),
    sa.Column('persona', sa.Enum('competitor', 'investor', 'hacker', 'customer', 'academic', name='persona_id'), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'major', 'minor', name='severity'), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggested_fix', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'downgraded', name='finding_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_finding_id'], ['persona_findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['stress_test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rebuttals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('user_response', sa.Text(), nullable=False),
    sa.Column('persona_counter_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rebuttals')
    op.drop_table('findings')
    op.drop_table('persona_findings')
    op.drop_table('stress_test_runs')
    op.drop_table('stress_test_projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
