import type {
  Persona,
  StressTestProject,
  StressTestRun,
  Finding,
  DialogueTurn,
  Rebuttal,
  TimelineEntry,
} from "@/models/types";

export const PERSONAS: Persona[] = [
  {
    id: "competitor",
    name: "Aggressive Competitor",
    shortLabel: "C",
    tagline: "Finds where you're vulnerable to being out-executed.",
    color: "var(--red)",
  },
  {
    id: "investor",
    name: "Cynical Investor",
    shortLabel: "I",
    tagline: "Attacks financial assumptions and unit economics.",
    color: "var(--amber)",
  },
  {
    id: "hacker",
    name: "Hacker / Red-Teamer",
    shortLabel: "H",
    tagline: "Scans for real vulnerability patterns in code.",
    color: "#3D5A80",
  },
  {
    id: "customer",
    name: "Skeptical Customer",
    shortLabel: "Cu",
    tagline: "Attacks the value proposition directly.",
    color: "var(--steel)",
  },
  {
    id: "academic",
    name: "Academic Reviewer",
    shortLabel: "AR",
    tagline: "Attacks methodology and novelty claims.",
    color: "#6B4E71",
  },
];

export const PROJECTS: StressTestProject[] = [
  {
    id: "d2c-skincare",
    title: "D2C Skincare Launch — Pitch v3",
    inputType: "business_plan",
    rawInputPreview:
      "Full pitch deck stress-tested against competitor, investor, and customer personas.",
    createdAt: "2026-08-28",
  },
  {
    id: "auth-service",
    title: "auth-service (GitHub repo)",
    inputType: "codebase",
    rawInputPreview:
      "Hacker persona pen-test style scan on the authentication microservice.",
    createdAt: "2026-08-20",
  },
  {
    id: "bangla-asr",
    title: "Bangla ASR Draft — Methodology",
    inputType: "research_paper",
    rawInputPreview:
      "Academic Reviewer persona attacking statistical validity and novelty claims.",
    createdAt: "2026-08-05",
  },
  {
    id: "seed-round-deck",
    title: "Seed Round Investor Deck",
    inputType: "pitch",
    rawInputPreview:
      "Cynical Investor persona attacking unit economics and market size claims.",
    createdAt: "2026-08-30",
  },
];

export const RUNS: StressTestRun[] = [
  {
    id: "run-d2c-1",
    projectId: "d2c-skincare",
    runNumber: 1,
    personasUsed: ["competitor", "investor", "customer"],
    status: "completed",
    createdAt: "2026-08-10",
    completedAt: "2026-08-10",
  },
  {
    id: "run-d2c-2",
    projectId: "d2c-skincare",
    runNumber: 2,
    personasUsed: ["competitor", "investor", "customer"],
    status: "completed",
    createdAt: "2026-08-19",
    completedAt: "2026-08-19",
  },
  {
    id: "run-d2c-3",
    projectId: "d2c-skincare",
    runNumber: 3,
    personasUsed: ["competitor", "investor", "customer"],
    status: "completed",
    createdAt: "2026-08-28",
    completedAt: "2026-08-28",
  },
  {
    id: "run-auth-1",
    projectId: "auth-service",
    runNumber: 1,
    personasUsed: ["hacker"],
    status: "completed",
    createdAt: "2026-08-20",
    completedAt: "2026-08-20",
  },
  {
    id: "run-asr-1",
    projectId: "bangla-asr",
    runNumber: 1,
    personasUsed: ["academic"],
    status: "completed",
    createdAt: "2026-07-22",
    completedAt: "2026-07-22",
  },
  {
    id: "run-asr-2",
    projectId: "bangla-asr",
    runNumber: 2,
    personasUsed: ["academic"],
    status: "completed",
    createdAt: "2026-08-05",
    completedAt: "2026-08-05",
  },
  {
    id: "run-seed-1",
    projectId: "seed-round-deck",
    runNumber: 1,
    personasUsed: ["investor"],
    status: "running",
    createdAt: "2026-08-30",
    completedAt: null,
  },
];

export const FINDINGS: Finding[] = [
  {
    id: "finding-cac",
    runId: "run-d2c-3",
    personaFindingId: "pf-investor-d2c",
    personaId: "investor",
    severity: "critical",
    category: "Unit Economics",
    title: "Unsupported CAC assumption",
    description:
      "Customer acquisition cost of $12 has no supporting data or case study — comparable brands report $35–50. This single assumption invalidates the entire unit economics model presented.",
    suggestedFix:
      "Provide a pilot campaign case study, or revise projections using a conservative $30–40 CAC range.",
    status: "downgraded",
  },
  {
    id: "finding-moat",
    runId: "run-d2c-3",
    personaFindingId: "pf-competitor-d2c",
    personaId: "competitor",
    severity: "major",
    category: "Defensibility",
    title: "No defensible moat against fast-followers",
    description:
      "Formulation and packaging can be replicated within 2–3 months by an existing player with distribution already in place. Nothing in the pitch addresses defensibility.",
    suggestedFix:
      "Articulate a specific defensibility angle — proprietary formulation, exclusive supplier, or community/brand moat.",
    status: "resolved",
  },
  {
    id: "finding-diff",
    runId: "run-d2c-3",
    personaFindingId: "pf-customer-d2c",
    personaId: "customer",
    severity: "minor",
    category: "Value Proposition",
    title: "Unclear differentiation from existing routine",
    description:
      '"Why would I switch from my current skincare routine" is not directly answered anywhere in the deck.',
    suggestedFix: "Add a direct before/after or switching-cost comparison slide.",
    status: "open",
  },
  {
    id: "finding-jwt-secret",
    runId: "run-auth-1",
    personaFindingId: "pf-hacker-auth-1",
    personaId: "hacker",
    severity: "major",
    category: "Secrets Management",
    title: "Hardcoded JWT secret fallback in source",
    description:
      "`config.js` falls back to a hardcoded string when `JWT_SECRET` is unset. Any deployment that forgets the env var silently signs tokens with a secret that's sitting in the git history.",
    suggestedFix: "Fail startup loudly if `JWT_SECRET` is missing — never fall back to a literal.",
    status: "open",
  },
  {
    id: "finding-rate-limit",
    runId: "run-auth-1",
    personaFindingId: "pf-hacker-auth-2",
    personaId: "hacker",
    severity: "major",
    category: "Brute Force",
    title: "No rate limiting on /login",
    description:
      "The login endpoint accepts unlimited attempts per IP and per account, making credential-stuffing and brute-force attacks trivial to run at scale.",
    suggestedFix: "Add per-IP and per-account rate limiting with exponential backoff and account lockout after N failed attempts.",
    status: "open",
  },
  {
    id: "finding-refresh-expiry",
    runId: "run-auth-1",
    personaFindingId: "pf-hacker-auth-3",
    personaId: "hacker",
    severity: "major",
    category: "Session Management",
    title: "Refresh tokens never expire",
    description:
      "Issued refresh tokens have no `exp` claim and are never revoked on logout, so a leaked token grants indefinite access.",
    suggestedFix: "Set a rolling expiry on refresh tokens and store an active-token allowlist that logout invalidates.",
    status: "open",
  },
  {
    id: "finding-stack-traces",
    runId: "run-auth-1",
    personaFindingId: "pf-hacker-auth-4",
    personaId: "hacker",
    severity: "minor",
    category: "Information Disclosure",
    title: "Verbose error messages leak stack traces",
    description:
      "500 responses in production include the full Node stack trace and internal file paths, handing an attacker a map of the codebase.",
    suggestedFix: "Return a generic error body in production and log the stack trace server-side only.",
    status: "open",
  },
  {
    id: "finding-security-headers",
    runId: "run-auth-1",
    personaFindingId: "pf-hacker-auth-5",
    personaId: "hacker",
    severity: "minor",
    category: "Hardening",
    title: "Missing security headers (CSP, HSTS)",
    description: "Responses omit Content-Security-Policy, Strict-Transport-Security, and X-Frame-Options headers.",
    suggestedFix: "Add `helmet` (or equivalent) with a locked-down default policy.",
    status: "open",
  },
  {
    id: "finding-cve-dep",
    runId: "run-auth-1",
    personaFindingId: "pf-hacker-auth-6",
    personaId: "hacker",
    severity: "minor",
    category: "Dependencies",
    title: "jsonwebtoken pinned to a version with a known CVE",
    description: "`jsonwebtoken@8.5.1` is affected by a signature-verification bypass fixed in 9.x.",
    suggestedFix: "Upgrade to `jsonwebtoken@9.x` and re-run the dependency audit in CI.",
    status: "open",
  },
  {
    id: "finding-significance",
    runId: "run-asr-2",
    personaFindingId: "pf-academic-asr-1",
    personaId: "academic",
    severity: "critical",
    category: "Statistical Validity",
    title: "WER improvement lacks confidence intervals",
    description:
      "The reported 2.1-point WER improvement over the baseline has no confidence interval or significance test, so it's unclear whether the gain is real or sampling noise.",
    suggestedFix: "Report bootstrapped confidence intervals or a paired significance test (e.g. MAPSSWE) alongside the point estimate.",
    status: "resolved",
  },
  {
    id: "finding-test-overlap",
    runId: "run-asr-1",
    personaFindingId: "pf-academic-asr-2",
    personaId: "academic",
    severity: "major",
    category: "Methodology",
    title: "Test set overlaps with training data by dialect region",
    description:
      "Several test-set speakers share a dialect region with training-set speakers with no held-out region split, inflating reported generalization.",
    suggestedFix: "Re-split by speaker and dialect region so no test region appears in training.",
    status: "resolved",
  },
  {
    id: "finding-novelty",
    runId: "run-asr-1",
    personaFindingId: "pf-academic-asr-3",
    personaId: "academic",
    severity: "major",
    category: "Novelty",
    title: "Novelty claim overstates delta versus prior Bangla ASR baselines",
    description:
      "The paper claims a 'novel architecture' but the described encoder is a near-identical Conformer variant already published in prior Bangla ASR work.",
    suggestedFix: "Either differentiate the architectural contribution explicitly or reframe the contribution around the dataset/results instead of architecture.",
    status: "resolved",
  },
  {
    id: "finding-iaa",
    runId: "run-asr-2",
    personaFindingId: "pf-academic-asr-4",
    personaId: "academic",
    severity: "minor",
    category: "Data Quality",
    title: "Missing inter-annotator agreement score",
    description: "Transcription labels were produced by human annotators, but no inter-annotator agreement metric is reported.",
    suggestedFix: "Report Cohen's kappa or WER-between-annotators on a shared subset.",
    status: "resolved",
  },
  {
    id: "finding-tam",
    runId: "run-seed-1",
    personaFindingId: "pf-investor-seed-1",
    personaId: "investor",
    severity: "critical",
    category: "Market Sizing",
    title: "TAM derived top-down with no bottoms-up cross-check",
    description:
      "The $4B TAM figure comes from a single industry report multiplied by a guessed penetration rate, with no bottoms-up validation from actual customer counts or pricing.",
    suggestedFix: "Build a bottoms-up TAM from realistic customer segments and price points, and reconcile it against the top-down number.",
    status: "open",
  },
  {
    id: "finding-burn",
    runId: "run-seed-1",
    personaFindingId: "pf-investor-seed-2",
    personaId: "investor",
    severity: "critical",
    category: "Runway",
    title: "18-month runway claim ignores planned headcount growth",
    description:
      "The burn-rate model holds headcount flat, but the same deck plans to double the team within 12 months — runway is closer to 9-11 months under that plan.",
    suggestedFix: "Model runway against the actual hiring plan, not a flat headcount assumption.",
    status: "open",
  },
  {
    id: "finding-arr-mix",
    runId: "run-seed-1",
    personaFindingId: "pf-investor-seed-3",
    personaId: "investor",
    severity: "major",
    category: "Revenue Quality",
    title: "ARR figure mixes annual and monthly contracts without disclosure",
    description: "Roughly a third of the quoted ARR comes from month-to-month customers, which is materially less durable than the annual-contract majority implied by the framing.",
    suggestedFix: "Break out ARR by contract term and disclose churn separately for monthly vs. annual cohorts.",
    status: "open",
  },
  {
    id: "finding-cac-payback",
    runId: "run-seed-1",
    personaFindingId: "pf-investor-seed-4",
    personaId: "investor",
    severity: "major",
    category: "Unit Economics",
    title: "CAC payback period omitted from unit economics slide",
    description: "LTV:CAC is quoted at 4.2x, but payback period isn't shown — a healthy ratio can still hide a payback period too slow for the proposed burn rate.",
    suggestedFix: "Add CAC payback period in months alongside the LTV:CAC ratio.",
    status: "open",
  },
  {
    id: "finding-comp-slide",
    runId: "run-seed-1",
    personaFindingId: "pf-investor-seed-5",
    personaId: "investor",
    severity: "major",
    category: "Competitive Landscape",
    title: "Competitive landscape slide omits the best-funded direct competitor",
    description: "A competitor that raised a $40M Series B six months ago targeting the identical segment is absent from the competitive matrix.",
    suggestedFix: "Add the competitor and articulate a specific differentiation versus their published feature set and pricing.",
    status: "open",
  },
  {
    id: "finding-cap-table",
    runId: "run-seed-1",
    personaFindingId: "pf-investor-seed-6",
    personaId: "investor",
    severity: "minor",
    category: "Cap Table",
    title: "Cap table slide doesn't show post-round dilution",
    description: "Founders' post-round ownership percentage after this raise isn't shown, which investors will ask for directly in diligence.",
    suggestedFix: "Add a pro-forma cap table showing ownership before and after the proposed round.",
    status: "open",
  },
  {
    id: "finding-advisor-equity",
    runId: "run-seed-1",
    personaFindingId: "pf-investor-seed-7",
    personaId: "investor",
    severity: "minor",
    category: "Cap Table",
    title: "Advisor equity grants not disclosed",
    description: "Two advisors are named in the deck with no disclosure of their equity grants, which affects fully-diluted ownership math.",
    suggestedFix: "Disclose advisor grant sizes and vesting in the cap table appendix.",
    status: "open",
  },
];

export const DIALOGUE: DialogueTurn[] = [
  {
    id: "d1",
    speaker: "persona",
    personaId: "investor",
    text: "Your CAC assumption of $12 seems optimistic for a new D2C skincare brand — most comparable launches in this category run $35–50. Where does $12 come from?",
  },
  {
    id: "d2",
    speaker: "user",
    text: "That's based on our influencer partnership model, which has lower acquisition cost than paid ads.",
  },
  {
    id: "d3",
    speaker: "persona",
    personaId: "investor",
    text: "Influencer-driven CAC still typically lands $20+ once you account for content production and management overhead — and you haven't shown a single case study proving your specific partnerships hit $12. This assumption is currently unsupported and materially affects your entire unit economics model.",
  },
];

export const REBUTTALS: Rebuttal[] = [
  {
    id: "reb-1",
    findingId: "finding-cac",
    userResponse:
      "We ran a 2-week micro-pilot with 3 nano-influencers and achieved $14 CAC on 200 conversions — small sample, but it's real data, not a guess.",
    personaCounterResponse:
      '200 conversions from 3 nano-influencers is not statistically reliable enough to underwrite a full unit economics model — investors will ask for at minimum a 1,000-conversion pilot before trusting this number at scale. I\'ll downgrade this from "unsupported" to "insufficiently validated," but it remains a blocking concern for a seed round.',
    createdAt: "2026-08-28",
  },
];

export const TIMELINE: TimelineEntry[] = [
  {
    id: "tl-3",
    projectId: "d2c-skincare",
    runId: "run-d2c-3",
    runNumber: 3,
    date: "Aug 28, 2026",
    title: "Pitch v3 — post-CAC-revision",
    summary:
      "Re-ran after updating unit economics with pilot data. 2 critical findings from Run #2 downgraded to major; 1 new minor finding surfaced.",
    resolvedCount: 0,
    criticalCount: 2,
    majorCount: 5,
    minorCount: 4,
    isResolvedMilestone: false,
  },
  {
    id: "tl-2",
    projectId: "d2c-skincare",
    runId: "run-d2c-2",
    runNumber: 2,
    date: "Aug 19, 2026",
    title: "Pitch v2 — added competitive moat slide",
    summary:
      "Competitor persona's \"no defensible moat\" finding from Run #1 marked resolved after moat slide was added.",
    resolvedCount: 1,
    criticalCount: 3,
    majorCount: 6,
    minorCount: 0,
    isResolvedMilestone: true,
  },
  {
    id: "tl-1",
    projectId: "d2c-skincare",
    runId: "run-d2c-1",
    runNumber: 1,
    date: "Aug 10, 2026",
    title: "Pitch v1 — initial stress test",
    summary:
      "First run across all 3 selected personas. Baseline: 4 critical, 7 major, 3 minor findings.",
    resolvedCount: 0,
    criticalCount: 4,
    majorCount: 7,
    minorCount: 3,
    isResolvedMilestone: false,
  },
];
